export const SECTORS = [
    'Administrativo',
    'Comercial',
    'Compras',
    'Custos',
    'Diretoria',
    'Ecommerce',
    'Financeiro',
    'Fabrica',
    'Logistica',
    'Marketing',
    'Qualidade',
    'RH',
    'T.I',
    'Regional Norte',
    'Regional Acessibilidade',
    'Regional Sao Paulo - Interior',
    'Regional Sudeste (MG/ES/RJ)',
    'Regional Sul',
    'Regional Nordeste',
    'Regional Sao Paulo - Capital',
    'Regional Centro-Oeste',
    'Regional Televendas',
    'Regional Leroy',
    'Regional B2B',
    'Gestão de Informação'
].sort();


export const MONTHS = ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'];

export const STRATEGIC_OBJECTIVES = [
    "Equipe Comercial Revenda",
    "Aumentar o volume de vendas em acessibilidade",
    "Reestruturação da Política Comercial",
    "Reestruturação da Equipe de Televendas",
    "Aumentar o numero de distribuidores",
    "Aumentar a presença em Home Center's",
    "Positivar mais clientes B2B",
    "Aumentar a presença nacional (redes)",
    "Aumentar a venda com frete CIF",
    "Mudança de Cultura Hierárquica para resultado e aprendizagem",
    "Desenvolver e Reter Talentos",
    "Desenvolver Lideranças",
    "Avaliação de Desempenho",
    "Captar Talentos (cargos chaves)",
    "Lançamento da linha de produtos recicláveis",
    "Ação sobre Não Conformidades",
    "Redução de desperdício",
    "Implantar planejamento de manutenções",
    "Desenvolver parcerias para novos produtos",
    "Desenhar e aprimorar os processos internos",
    "Agilizar lançamento de produtos",
    "Conta corrente tributário",
    "Aumento da rentabilidade",
    "Redução de custos",
    "Carro elétrico",
    "Melhoria Compras",
    "Melhoria Logística",
    "Estrutura equipe Supply",
    "Melhorar a comunicação no PDV",
    "Calendário de Ações Comerciais",
    "Marketing da Empresa:  Fortalecer a presença institucional da 3LACKD, garantindo comunicação profissional, padronizada e eficiente em todos os pontos de contato; aprimorar materiais comerciais e de PDV; modernizar a identidade visual; ampliar a presença digital; e criar processos organizados que apoiem representantes, vendas e lançamentos de produtos.",
    "Lançamento de Produtos / Importação",
    "AE (Acompanhamento e Efetividade)",
    "PDI's (Desenvolver e Reter)",
    "Treinamento Trabalho em equipe",
    "Entrevista Desligamento",
    "Recrutamento & Seleção",
    "Integração (Mudança de Cultura Hierárquica para resultado e aprendizagem)",
    "Desenvolvimento dos líderes",
    "Descrição de cargos",
    "Indicadores",
    "Redução de custos",
    "Segurança patrimonial, física e registro de acessos",
    "Continuidade do negócio",
    "Contratação e implantação de um novo ERP",
    "Evolução e ampliação da operação B2C"
].sort();

export const MAX_FILE_SIZE_MB = 50;
export const MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024;
